project:
  type: website

website:
  title: "Applied Bioinformatics"
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/amrei-bp/Applied_Bioinformatics_MedBioInfo_2025
          - text: Report a Bug
            href:  https://github.com/amrei-bp/Applied_Bioinformatics_MedBioInfo_2025/issues
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  search: 
    location: navbar
    type: textbox

  sidebar:
    style: "docked"
    search: true
    logo: figures/logo/SLUBI_logo.png
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Before the course"
        contents:
          - before_accounts.qmd
          - before_VScode.qmd
          - before_server.qmd
          - before_command_line.qmd
          - before_screen.qmd
          - before_quarto.qmd
          - before_git_and_github.qmd


      - section: "During the course"
        contents:
          - course_intro.qmd
          - course_data_management.qmd
          - course_git.qmd
          - course_blog.qmd
          - course_publish_blog.qmd
          - course_environments.qmd
          - course_qc.qmd
          - course_container.qmd
          - course_nf-core.qmd
          - course_test_nf-core.qmd
          - course_nf-core_rnaseq.qmd
          - course_ggplot.qmd
          - course_AI.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    highlight-style: github
    code-overflow: wrap

execute:
  freeze: auto

