project:
  type: website

website:
  title: "Applied Bioinformatics"
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/amrei-bp/Applied_Bioinformatics_MedBioInfo_2025
          - text: Report a Bug
            href:  https://github.com/amrei-bp/Applied_Bioinformatics_MedBioInfo_2025/issues
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  search: 
    location: navbar
    type: textbox

  sidebar:
    style: "docked"
    search: true
    logo: figures/logo/SLUBI_logo.png
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Before the course"
        contents:
          - before_VScode.qmd
          - before_quarto.qmd
          - before_git_and_github.qmd
          - before_quarto_and_git.qmd
          - before_server.qmd


      - section: "During the course"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    highlight-style: github
    code-overflow: wrap

execute:
  freeze: auto

