---
title: "Command line"
---

Unix-like operating systems are built under the model of free and open-source development and distribution. They often come with a graphical user interface (GUI) and can be run from the command line (CLI) or terminal. The CLI is a text-based interface that works exactly the same way as you would use your mouse, but you use words. It can be intimidating at first, but once you have mastered the basics, it's really not different than using your mouse!

It is important to know how to use the terminal as all servers, and most bioinformatics tools do not have a GUI and rely on the use of the terminal.

For this course, we will use a GUI for some parts, but all our interaction with the remote server will be on the command line. As such, it's important that you know your way around the command line. 

::: {.callout-important}
## To do for you

I know that you have varying proficiency with the command line. 

Please follow this excellent [software carpentries tutorial on the Unix shell](https://swcarpentry.github.io/shell-novice/). 
:::