on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # install R and R packages
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::tidyr
            any::ggplot2
            any::palmerpenguins
            any::kableExtra
            any::patchwork
            any::plotly
            any::ggiraph

      # set up Quarto and render
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: homepage  # Specify the path to your Quarto project

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: homepage  # Specify the path to your Quarto project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
